<a href="https://colab.research.google.com/github/JakeOh/202505_BD50/blob/main/lab_da/da03_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import seaborn as sns

# 예제 데이터셋 가져오기

In [2]:
tips = sns.load_dataset('tips')

In [6]:
tips.head()  # tips.iloc[:5] 같은 기능

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

# 연습문제

*   DataFrame의 행과 열의 개수
*   열(column) 이름들
*   마지막 6개 행을 출력
*   DataFrame의 요약 정보
*   숫자 타입 변수(컬럼)의 기술 통계량
*   카테고리 타입 변수의 빈도수
*   total_bill 컬럼의 값이 최댓값인 행을 출력
*   total_bill 컬럼의 값이 최솟값인 행을 출력
*   남성들의 tip의 평균
*   여성들의 tip의 평균
*   일요일의 tip의 평균
*   일요일 남성의 tip의 평균
*   일요일 여성의 tip의 평균

In [7]:
tips.shape

(244, 7)

In [9]:
print('# of rows:', tips.shape[0])
print('# of columns:', tips.shape[1])

# of rows: 244
# of columns: 7

In [10]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [12]:
for c in tips.columns:
    print(c)

total_bill
tip
sex
smoker
day
time
size

In [13]:
tips.tail(n=6)

     total_bill   tip     sex smoker   day    time  size
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [18]:
tips.iloc[-6:]

     total_bill   tip     sex smoker   day    time  size
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [19]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [20]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [21]:
tips.sex.value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [22]:
tips.smoker.value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [23]:
tips.day.value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [25]:
tips.time.value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [29]:
tips['size'].value_counts()

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [35]:
tips.total_bill.max()

50.81

In [37]:
tips.total_bill == tips.total_bill.max()

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Name: total_bill, Length: 244, dtype: bool

In [38]:
tips[tips.total_bill == tips.total_bill.max()]

     total_bill   tip   sex smoker  day    time  size
170       50.81  10.0  Male    Yes  Sat  Dinner     3

In [39]:
tips[tips.total_bill == tips.total_bill.min()]

    total_bill  tip     sex smoker  day    time  size
67        3.07  1.0  Female    Yes  Sat  Dinner     1

In [40]:
tips[(tips.total_bill == tips.total_bill.max()) |
    (tips.total_bill == tips.total_bill.min())]

     total_bill   tip     sex smoker  day    time  size
67         3.07   1.0  Female    Yes  Sat  Dinner     1
170       50.81  10.0    Male    Yes  Sat  Dinner     3

In [43]:
tips[tips.sex == 'Male'].tip.mean()

np.float64(3.0896178343949043)

In [47]:
tips[tips.sex == 'Female'].tip.mean()

np.float64(2.8334482758620685)

In [50]:
tips[tips.day == 'Sun'].tip.mean()

np.float64(3.2551315789473687)

In [53]:
tips[tips.day == 'Sat'].tip.mean()

np.float64(2.993103448275862)

In [62]:
tips[(tips.day == 'Sun') & (tips.sex == 'Male')].tip.mean()

np.float64(3.2203448275862065)

In [57]:
tips[(tips.day == 'Sun') & (tips.sex == 'Female')].tip.mean()

np.float64(3.3672222222222223)

In [59]:
tips[tips.tip > tips.tip.mean()]

     total_bill   tip     sex smoker   day    time  size
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
7         26.88  3.12    Male     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
232       11.61  3.39    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
243       18.78  3.00  Female     No  Thur  Dinner     2

[121 rows x 7 columns]

## 파생변수

In [63]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [64]:
tips.tip / tips.total_bill

0      0.059447
1      0.160542
2      0.166587
3      0.139780
4      0.146808
         ...
239    0.203927
240    0.073584
241    0.088222
242    0.098204
243    0.159744
Length: 244, dtype: float64

In [72]:
# 데이터프레임에 파생변수(새로운 컬럼) 추가
tips['tip_ratio'] = tips.tip / tips.total_bill

In [73]:
tips.head()

   total_bill   tip     sex smoker  day    time  size  tip_ratio
0       16.99  1.01  Female     No  Sun  Dinner     2   0.059447
1       10.34  1.66    Male     No  Sun  Dinner     3   0.160542
2       21.01  3.50    Male     No  Sun  Dinner     3   0.166587
3       23.68  3.31    Male     No  Sun  Dinner     2   0.139780
4       24.59  3.61  Female     No  Sun  Dinner     4   0.146808

*   팁/영수증 비율의 평균값
*   팁/영수증 비율이 평균보다 큰 데이터
*   팁/영수증 비율이 평균보다 큰 데이터 중에서 남성/여성의 비율

In [74]:
tips.tip_ratio.mean()

np.float64(0.16080258172250472)

In [76]:
df = tips[tips.tip_ratio > tips.tip_ratio.mean()]

In [77]:
df.head()

    total_bill   tip   sex smoker  day    time  size  tip_ratio
2        21.01  3.50  Male     No  Sun  Dinner     3   0.166587
5        25.29  4.71  Male     No  Sun  Dinner     4   0.186240
6         8.77  2.00  Male     No  Sun  Dinner     2   0.228050
9        14.78  3.23  Male     No  Sun  Dinner     2   0.218539
10       10.27  1.71  Male     No  Sun  Dinner     2   0.166504

In [78]:
df.sex.value_counts()

sex
Male      66
Female    41
Name: count, dtype: int64

In [80]:
tips.sex.value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [79]:
df.sex.value_counts() / tips.sex.value_counts()

sex
Male      0.420382
Female    0.471264
Name: count, dtype: float64

# titanic 데이터셋

In [81]:
titanic = sns.load_dataset('titanic')

In [82]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

titanic 데이터프레임 컬럼

*   survived: 생존 여부(0=사망, 1=생존)
    *   alive 컬럼과 같은 내용(no=사망, yes=생존)
*   pclass: 객실 등급
    *   class 컬럼과 같은 내용(1=First, 2=Second, 3=Third, ...)
*   sex: 성별(male/female)
*   who: 성인남성(man), 성인여성(woman), 어린이(child)
*   adult_male: 성인 남성 여부(True/False)
*   age: 나이
*   sibsp: 동승한 형제자매 또는 배우자의 수
*   parch: 동승한 부모 또는 자녀의 수
*   alone: 혼자 탑승했는 지 여부(True/False)
*   fare: 탑승권 가격. 운임.